### ISSUE TITLE
s/humanReadableName/name

### ISSUE THREAD

**Issue by beaufortfrancois** [tomayac/cross-origin-storage#2]
I would rename `humanReadableName` to `name` and state in the spec that the name must be human-readable.

```diff
  Promise<FileSystemFileHandle> getFileHandle(
      DOMString hash,
-     DOMString humanReadableName,
+     DOMString name,
      // https://fs.spec.whatwg.org/#dictdef-filesystemgetfileoptions
      optional FileSystemGetFileOptions options = {});
};
```

**Comment by tomayac** [comment]
This makes sense to me. Is there a spec'y way to say it should correspond to "classic file name rules" (as hand wavy as this is)?

**Comment by tomayac** [comment]
This seems reasonble:
> Human-readable names must consist of valid Unicode characters, avoid restricted characters like `/:*?"<>|`, and should be no longer than 255 characters.
