### ISSUE TITLE
Expand use cases with JS libraries

### ISSUE THREAD

**Issue by beaufortfrancois** [tomayac/cross-origin-storage#5]
> COS aims to:
> - Provide a cross-origin storage mechanism for web applications to store and retrieve large files like AI models, SQLite databases, offline storage archives, and Wasm modules.

I believe developers relying on popular JS libraries may find this helpful as well. Think JQuery for instance whose share was 10x other popular JavaScript libraries according to  https://blog.cloudflare.com/radar-2024-year-in-review/

**Comment by tomayac** [comment]
I was initially not considering this, based on the [impact metrics](https://github.com/shivanigithub/http-cache-partitioning?tab=readme-ov-file#impact-on-metrics) from the HTTP cache partitioning effort. Fragmentation seems to be the biggest problem in JavaScript library land. 

Maybe worth adding as an FAQ entry linking to those stats?!

**Comment by tomayac** [comment]
Also [from the same explainer](https://github.com/shivanigithub/http-cache-partitioning?tab=readme-ov-file#impact-on-metrics:~:text=As%20mentioned%20in,1.5%20percentage%20points.):

> As mentioned in the metrics details below, preliminary experiments with partitioning show that the overall cache miss rate increases by about 2 percentage points but changes to first contentful paint aren’t statistically significant and the overall fraction of bytes loaded from the network only increase by around 1.5 percentage points.

**Comment by beaufortfrancois** [comment]
Thanks for sharing those stats!
An FAQ entry may be worth adding then for people like me ;)
